const headers = [
    { text: '', value: 'select', sortable: false },
    { text: '#', },
    {
        text: 'Tracking ID',
        align: 'start',
        value: 'trackingId',
        sortable: false,
    },
    {
        text: 'Pickup Round',
        align: 'start',
        value: 'pickupRound',
        sortable: false,
    },
    {
        text: 'Size',
        align: 'start',
        value: 'size',
        sortable: false,
    },
    {
        text: 'COD',
        align: 'start',
        value: 'cod',
        sortable: false,
    },
    {
        text: 'Temp Control',
        align: 'start',
        value: 'tempControl',
        sortable: false,
    },
    {
        text: 'Service Date',
        align: 'start',
        value: 'serviceDate',
        width: '7.5rem',
        sortable: false,
    },
    {
        text: 'Sender Name',
        align: 'start',
        value: 'senderName',
        width: '12.5rem',
        sortable: false,
    },
    {
        text: 'Sender Phone',
        align: 'start',
        value: 'senderPhone',
        width: '7rem',
        sortable: false,
    },
    {
        text: 'Sender Address',
        align: 'start',
        value: 'senderAddress',
        width: '30rem',
        sortable: false,
    },
    {
        text: 'Sender District',
        align: 'start',
        value: 'senderDistrict',
        sortable: false,
    },
    {
        text: 'Sender Postcode',
        align: 'start',
        value: 'senderPostcode',
        sortable: false,
    },
    {
        text: 'Receiver Name',
        align: 'start',
        value: 'receiverName',
        width: '7.5rem',
        sortable: false,
    },
    {
        text: 'Receiver Phone',
        align: 'start',
        value: 'receiverPhone',
        width: '7rem',
        sortable: false,
    },
    {
        text: 'Receiver Address',
        align: 'start',
        value: 'receiverAddress',
        width: '30rem',
        sortable: false,
    },
    {
        text: 'Receiver District',
        align: 'start',
        value: 'receiverDistrict',
        sortable: false,
    },
    {
        text: 'Receiver Postcode',
        align: 'start',
        value: 'receiverPostcode',
        sortable: false,
    },
    {
        text: 'Delivery Status',
        align: 'start',
        value: 'deliveryStatus',
        sortable: false,
    },
    {
        text: 'Parcel Type',
        align: 'start',
        value: 'parcelType',
        sortable: false,
    },
    {text: 'Remove', align: 'start', value: 'remove', sortable: false},
];

export default headers;