const tasks = [
    {
        trackingId: 'EX0000000001',
        pickupRound: 1,
        size: 'S100',
        cod: 500,
        tempControl: 0,
        serviceDate: '2021-07-31',
        senderName: 'test sender 1 test sender 2 test sender 3',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000002',
        pickupRound: 1,
        size: 'S100',
        cod: 199,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000003',
        pickupRound: 1,
        size: 'S100',
        cod: 300,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000004',
        pickupRound: 1,
        size: 'S100',
        cod: 100,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000005',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000006',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000007',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000008',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000009',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000010',
        pickupRound: 1,
        size: 'S100',
        cod: 0,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000011',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000012',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000013',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000014',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000015',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000016',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000017',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
    {
        trackingId: 'EX0000000018',
        pickupRound: 1,
        size: 'S100',
        cod: 999,
        tempControl: 0,
        serviceDate: '2021-07-01',
        senderName: 'test sender 1',
        senderPhone: '0123456789',
        senderAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Bang Sue, 10800',
        senderDistrict: 'Bang Sue',
        senderPostcode: '10800',
        receiverName: 'test receiver 1',
        receiverPhone: '9876543210',
        receiverAddress:
            'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis, sed sint provident sequi eligendi aut veritatis, Klong Toei, 10110',
        receiverDistrict: 'Klong Toei',
        receiverPostcode: '10100',
        deliveryStatus: 'delivering',
        parcelType: 'Bakery',
        confirmed: false,
    },
];
export default tasks;